YouTube: Move in iframe_api and www-widgetapi.js: Fix for Google Tag Manager
Google Tag Manager tries to access YouTube Player API for the FV Player YouTube iframe.
But snce we load our own copy of YouTube Player API as FV_YT, it fails with error:

a.getDuration is not a function

Internally Google Tag Manager sets attribute like data-gtm-yt-inspected-{number} on the iframe.
So we set it ourselves.

The number appears to be 8.
But looking at the inner workings, it depends on window.google_tag_manager.sequence,
which seems to increase as it adds more and more hooks.
So we use all of 0 to window.google_tag_manager.sequence for data-gtm-yt-inspected-{number}