HLS.js upgrade from 1.6.5 to 1.6.9
This helps with the video playback pausing for a fraction of second and then resuming automatically:

QuotaExceededError: Failed to execute 'appendBuffer' on 'SourceBuffer': The SourceBuffer is full, and cannot free space to append additional buffers.